In [1]:
import numpy as np
a=np.array([1,2,3,4])
print("One dimensional array:",a)

One dimensional array: [1 2 3 4]


In [2]:
import numpy as np
b=np.array([[1,2,3,4],[5,6,7,8]])
print("Two dimensional array:",b)

Two dimensional array: [[1 2 3 4]
 [5 6 7 8]]


In [3]:
import numpy as np
c=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Three dimensional array:",c)

Three dimensional array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
import numpy as np
d=np.zeros((3,5))
print("\n Array with all zeros\n",d)


 Array with all zeros
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
import numpy as np
e=np.random.random((3,5))
print("\n Random value\n",e)


 Random value
 [[0.71864137 0.19564765 0.83781352 0.37156376 0.31599671]
 [0.06433179 0.73427538 0.8528099  0.02022083 0.44068574]
 [0.19839705 0.38026839 0.50150051 0.61197272 0.55278485]]


In [6]:
import numpy as np
f=np.random.random((3,5))
print("\n Random value\n",f)


 Random value
 [[0.38085243 0.18921303 0.15729519 0.52564462 0.57374833]
 [0.34735294 0.33513557 0.60543102 0.03251976 0.95716188]
 [0.0579005  0.04143572 0.01219367 0.81589875 0.04050382]]


In [7]:
import numpy as np
a=np.arange(0,10,1)
print("\n sequence value:\n",a)


 sequence value:
 [0 1 2 3 4 5 6 7 8 9]


In [8]:
import numpy as np
b=np.arange(0,36,5)
print("\n sequence value:\n",b)


 sequence value:
 [ 0  5 10 15 20 25 30 35]


In [10]:
import numpy as np
orgarr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr=orgarr.reshape(4,3)
print("\n original array:\n",orgarr)
print("\n reshaped array:\n",newarr)


 original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 reshaped array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
import numpy as np
orgarr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24],[25,26,27,28,29,30]])
newarr=orgarr.reshape(6,5)
print("\n original array:\n",orgarr)
print("\n reshaped array:\n",newarr)


 original array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]

 reshaped array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [18]:
import numpy as np
orgarr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr=orgarr.flatten()
print("\n original array:\n",orgarr)
print("\n flatten array:\n",newarr)


 original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 flatten array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [19]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("\n no of dimension \n",a.ndim)


 no of dimension 
 2


In [21]:
import numpy as np
b=np.array([1,2,3])
print("\n no of dimension \n",b.ndim)


 no of dimension 
 1


In [28]:
import numpy as np
c=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print("\n no of dimension \n",c.ndim)


 no of dimension 
 3


In [29]:
import numpy as np
d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("\n shape of the array \n",d.shape)


 shape of the array 
 (3, 4)


In [30]:
import numpy as np
e=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("\n type of array:\n",e.dtype)


 type of array:
 int64


In [1]:
import numpy as np
a=[1,2,3]
a=np.array(a)
newtype=a.astype('float64')
print(newtype)
print(newtype.dtype)


[1. 2. 3.]
float64
