In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice1=arr[2:6]
print(slice1)

[3 4 5 6]


In [8]:
slice2=arr[::2]
print(slice2)

[1 3 5 7 9]


In [11]:
import numpy as np
arr=([1,2,3,4,5,6,7,8,9])
reversed_arr=arr[::-1]
print(reversed_arr)

[9, 8, 7, 6, 5, 4, 3, 2, 1]


In [10]:
slice3=arr[::3]
print(slice3)

[1 4 7]


In [12]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray=arr[0:2,1:3]
print(subarray)

[[2 3]
 [5 6]]


In [13]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[:2,:1])

[[1]
 [4]]


In [14]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])                      
col1=arr[:,0]
print(col1)

[1 4 7]


In [15]:
import numpy as np
row1=arr[0,:]
print(row1)

[1 2 3]


In [18]:
import numpy as np
import array
arr=array.array('i',[10,20,30,40,50])
print(arr[0])
print(arr[3])

10
40


In [21]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,0])
print(arr[2,1])

1
8


In [23]:
import numpy as np
arr=([10,20,30])
print(arr[1])

20


In [24]:
import numpy as np
print(arr[-1])

30


In [25]:
import numpy as np
arr=([10,20,30,40,50,60,70])
print(arr[1:4])

[20, 30, 40]


In [27]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[arr>25])

[30 40 50]


In [30]:
import numpy as np
print(arr[[1,3]])

[20 40]


In [1]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [2]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.vstack((arr1,arr2))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [3]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.dstack((arr1,arr2))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
result=np.split(arr,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [5]:
import numpy as np
arr=np.array([1,2,3,4,5])
result=np.array_split(arr,5)
print(result)

[array([1]), array([2]), array([3]), array([4]), array([5])]
